/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

type Artifact struct {
	Kind string `json:"kind,omitempty"`
	JarUri string `json:"jarUri,omitempty"`
	MainArgs string `json:"mainArgs,omitempty"`
	FlinkVersion float64 `json:"flinkVersion,omitempty"`
	FlinkImageResgistry string `json:"flinkImageRegistry,omitempty"`
	FLinkImageRepository string `json:"flinkImageRepository,omitempty"`
	FlinkImageTag string `json:"flinkImageTag,omitempty"`
}
