/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

type Pods struct {
	Affinity *JsonNode `json:"affinity,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
	EnvVars []EnvVar `json:"envVars,omitempty"`
	ImagePullSecrets []LocalObjectReference `json:"imagePullSecrets,omitempty"`
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	SecurityContext *JsonNode `json:"securityContext,omitempty"`
	Tolerations []JsonNode `json:"tolerations,omitempty"`
	VolumeMounts []VolumeAndMount `json:"volumeMounts,omitempty"`
}
