/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

type DeploymentSpec struct {
	State string `json:"state,omitempty"`
	UpgradeStrategy *DeploymentUpgradeStrategy `json:"upgradeStrategy,omitempty"`
	RestoreStrategy *DeploymentRestoreStrategy `json:"restoreStrategy,omitempty"`
	DeploymentTargetId string `json:"deploymentTargetId,omitempty"`
	MaxSavepointCreationAttempts int32 `json:"maxSavepointCreationAttempts,omitempty"`
	MaxJobCreationAttempts int32 `json:"maxJobCreationAttempts,omitempty"`
	Template *DeploymentTemplate `json:"template,omitempty"`
}
