/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

import (
	"time"
)

type LicenseSpec struct {
	Expires time.Time `json:"expires,omitempty"`
	LicenseId string `json:"licenseId,omitempty"`
	LicensedTo string `json:"licensedTo,omitempty"`
	Params map[string]string `json:"params,omitempty"`
}
