/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

type SystemInformationStatus struct {
	JvmVersion string `json:"jvmVersion,omitempty"`
	License *License `json:"license,omitempty"`
	ResourceQuota *ResourceQuota `json:"resourceQuota,omitempty"`
	RevisionInformation *RevisionInformation `json:"revisionInformation,omitempty"`
}
