/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

type EnvVar struct {
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
	ValueFrom *ValueFrom `json:"valueFrom,omitempty"`
}

type ValueFrom struct {
	FieldRef *FieldRef `json:"fieldRef,omitempty"`
}

type FieldRef struct {
	FieldPath string `json:"fieldPath,omitempty"`
}
