/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.0.1
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vapi

type EventMetadata struct {
	CreatedAt       string `json:"createdAt,omitempty"`
	DeploymentId    string `json:"deploymentId,omitempty"`
	Id              string `json:"id,omitempty"`
	JobId           string `json:"jobId,omitempty"`
	Name            string `json:"name,omitempty"`
	Namespace       string `json:"namespace,omitempty"`
	ResourceVersion int32  `json:"resourceVersion,omitempty"`
}
